#include "Menu.h"
#include <iostream>

using namespace std;

void Menu::InformUser()
{
    cout << "\n This app simulates a possible tracking app that uses the gps singals from your devide. This app doesnt track any of your movements or store them in anyway.";
    cout << "\n Every movement is random generated by rand using the RandomWaypoint model";
}
void Menu::PrintMenu()
{
    cout << "\n -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------";
    cout << "\n Menu";
    cout << "\n Start The Tracking Proccess...\n";
}
void Menu::PrintEndofDay()
{
    cout << "\n This is the end of these day , the user is still not infected , do you want to continue";
}
void Menu::AvailableUserFunctions()
{
    cout << "\n 1.Find crowed/hotspot places";
    cout << "\n 2.Exit";
}

void Menu::PromtForSimulation()
{
    cout << "\n Your were infected ,  do you want to run the simualtion for all users ?";
}

void Menu::PromtForFunctions()
{
    cout << "\n Choose from the above menu: ";
    cout << "\n 1.Find possible hotspots";
    cout << "\n 2.Continue to the next day";
    cout << "\n 3. Exit the programm";
}