#include "../headers/Menu.h"
#include <iostream>

using namespace std;

void Menu::InformUser()
{
    cout << "\n This app simulates a possible tracking app that uses the gps singals from your devide. This app doesnt track any of your movements or store them in anyway.";
    cout << "\n Every movement is random generated by rand using the RandomWaypoint model";
}
void Menu::PrintMenu()
{
    cout << "\n -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------";
    cout << "\n Menu";
    cout << "\n Start The Tracking Proccess...\n";
}
void Menu::PromtForSimulation()
{
    cout << "\n User has to be informed please go check your Goverment Health Administration";
}

void Menu::PromtForFunctions()
{
    cout << "\n Choose from the above menu: ";
    cout << "\n 1.Find possible hotspots";
    cout << "\n 2.Continue to the next day";
    cout << "\n 3.Dont promt again and run simulation till the end";
    cout << "\n 4 . Exit the programm";
}